theme = "edge"

[editor]
auto-save = true
true-color = true
bufferline = "multiple"

[editor.cursor-shape]
normal = "block"
insert = "bar"

[keys.insert]
C-a = "goto_line_start"
C-e = "goto_line_end_newline"
A-b = "move_prev_word_end"
A-f = "move_next_word_start"

[keys.normal]
X = "extend_line_above"
esc = "keep_primary_selection"

