theme = "edge"

[editor]
true-color = true
bufferline = "multiple"

[editor.cursor-shape]
normal = "block"

[keys.insert]
C-space = "completion"
C-a = "goto_first_nonwhitespace"
C-e = "goto_line_end_newline"
A-b = ["move_prev_word_start", "collapse_selection"]
A-f = ["move_next_word_start", "move_char_right"]

[keys.normal]
C-a = "goto_first_nonwhitespace"
C-e = "goto_line_end_newline"
A-b = ["move_prev_word_start", "collapse_selection"]
A-f = ["move_next_word_start", "move_char_right"]
"[" = { "b" = ":buffer-previous" }
"]" = { "b" = ":buffer-next" }

