gui:
  showFileTree: false
  theme:
    activeBorderColor:
      - '#ae8e57'
    inactiveBorderColor:
      - '#424b56'
    selectedLineBgColor:
      - '#1e293b'
      - default
    inactiveViewSelectedLineBgColor:
      - '#2c2e33'
      - 'default'
git:
  autoFetch: false
  paging:
    colorArg: always
    useConfig: true
