gui:
  showFileTree: false
  theme:
    inactiveBorderColor:
      - '#424b56'
    selectedLineBgColor:
      - '#1e293b'
      - default
    inactiveViewSelectedLineBgColor:
      - '#2c2e33'
      - 'default'
